# Generated by Django 2.1.5 on 2019-02-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'managed': False},
        ),
    ]
