# Generated by Django 2.1.5 on 2019-02-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190206_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='anger',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='disgust',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='fear',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='happiness',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name_id',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='neutral',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='sadness',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='surprise',
        ),
        migrations.AddField(
            model_name='photo',
            name='json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_id',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
